--DROP DATABASE ROOMSCHEDULER;

-- create statements

CREATE DATABASE ROOMSCHEDULER;

USE ROOMSCHEDULER;

CREATE TABLE FACULTY(FACULTYNAME VARCHAR(20) PRIMARY KEY , FNAME VARCHAR(20), DEPT VARCHAR(20));
CREATE TABLE DATES (DATE CHAR(5) PRIMARY KEY); -- DD-MM format
CREATE TABLE WAITLIST(DATE CHAR(5), FACULTYNAME VARCHAR(20), QUEUE INT, 
							FOREIGN KEY(DATE) REFERENCES DATES(DATE),
							FOREIGN KEY(FACULTYNAME) REFERENCES FACULTY(FACULTYNAME));

CREATE TABLE ROOMS (RMNO CHAR(3) PRIMARY KEY, SEATS INT(3));

CREATE TABLE RESERVATIONS (RMNO CHAR(3),FACULTYNAME VARCHAR(20),DATE CHAR(5),
							FOREIGN KEY(DATE) REFERENCES DATES(DATE),
							FOREIGN KEY(FACULTYNAME) REFERENCES FACULTY(FACULTYNAME),
							FOREIGN KEY(RMNO) REFERENCES ROOMS(RMNO));
							



-- insert statements

-- date insert
INSERT INTO DATES(DATE) VALUES ("01-12");
INSERT INTO DATES(DATE) VALUES ("02-12");
INSERT INTO DATES(DATE) VALUES ("03-12");
INSERT INTO DATES(DATE) VALUES ("04-12");
INSERT INTO DATES(DATE) VALUES ("05-12");
INSERT INTO DATES(DATE) VALUES ("06-12");
INSERT INTO DATES(DATE) VALUES ("07-12");
INSERT INTO DATES(DATE) VALUES ("08-12");
INSERT INTO DATES(DATE) VALUES ("09-12");
INSERT INTO DATES(DATE) VALUES ("10-12");

-- faculty insert
INSERT INTO FACULTY(FACULTYNAME,FNAME,DEPT) VALUES ("Toriumi","Isako","English");
INSERT INTO FACULTY(FACULTYNAME,FNAME,DEPT) VALUES ("Taylor","Jamie","English");
INSERT INTO FACULTY(FACULTYNAME,FNAME,DEPT) VALUES ("Parker","Richard","English");
INSERT INTO FACULTY(FACULTYNAME,FNAME,DEPT) VALUES ("Wayne","Thomas","English");
INSERT INTO FACULTY(FACULTYNAME,FNAME,DEPT) VALUES ("Jameson","May","English");

-- rooms insert
INSERT INTO ROOMS(RMNO, SEATS) VALUES ("101", 10);
INSERT INTO ROOMS(RMNO, SEATS) VALUES ("102", 20);
INSERT INTO ROOMS(RMNO, SEATS) VALUES ("103", 30);
INSERT INTO ROOMS(RMNO, SEATS) VALUES ("104", 40);
INSERT INTO ROOMS(RMNO, SEATS) VALUES ("105", 50);

SELECT* FROM FACULTY;
SELECT* FROM DATES;
SELECT* FROM ROOMS;




